apiVersion: v1
kind: Service
metadata:
  name: arranger
  namespace: arranger
  labels:
    app.kubernetes.io/name: arranger
spec:
  selector:
    app.kubernetes.io/name: arranger
  ports:
    - name: http
      port: 80
      targetPort: http
