"""Where uploaded and generated files live.

Metadata (owner, kind, size, hash) is in the `artifacts` table. The bytes are
behind `ArtifactStore`, so a deployment can keep them on a disk, in the
database, or in S3-compatible object storage without any route changing.

Keys are generated by this service (`<user>/<uuid>.<ext>`), never taken from a
filename, and every adapter still validates them: a key is the one string that
ends up in a filesystem path or a URL.

Nothing here decides who may read a file. Routes authorise against the
`artifacts` row first and only then ask the store for bytes.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import hmac
import re
import uuid
from pathlib import Path
from typing import Any, Protocol
from urllib.parse import quote

_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{0,63}(/[A-Za-z0-9][A-Za-z0-9._-]{0,127}){1,3}$")

CONTENT_TYPES = {
    "midi": ("audio/midi", "mid"),
    "musicxml": ("application/vnd.recordare.musicxml+xml", "musicxml"),
    "mxl": ("application/vnd.recordare.musicxml", "mxl"),
    "pdf": ("application/pdf", "pdf"),
    "json": ("application/json", "json"),
    "zip": ("application/zip", "zip"),
    "upload": ("application/octet-stream", "bin"),
}


class ArtifactError(RuntimeError):
    """The store could not complete the operation."""


class ArtifactNotFound(ArtifactError):
    pass


def new_storage_key(user_id: str, kind: str) -> str:
    extension = CONTENT_TYPES.get(kind, CONTENT_TYPES["upload"])[1]
    return f"{check_key_part(user_id)}/{uuid.uuid4().hex}.{extension}"


def check_key_part(value: str) -> str:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{0,63}", value or ""):
        raise ArtifactError("invalid storage key component")
    return value


def check_key(key: str) -> str:
    """Reject anything that is not a plain, relative, generated-looking key."""
    if not isinstance(key, str) or not _KEY.fullmatch(key) or ".." in key:
        raise ArtifactError("invalid storage key")
    return key


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def safe_filename(name: str, fallback: str) -> str:
    """A download filename: no path, no control characters, no header injection."""
    base = (name or "").replace("\\", "/").rsplit("/", 1)[-1]
    cleaned = "".join(ch for ch in base if ch.isalnum() or ch in " ._-()").strip(" .")
    return cleaned[:120] or fallback


class ArtifactStore(Protocol):
    name: str

    def put(self, key: str, data: bytes, content_type: str) -> None: ...
    def get(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def healthy(self) -> bool: ...


class LocalArtifactStore:
    """Files under one directory. The right choice for development and single-host deploys."""

    name = "local"

    def __init__(self, root: str | Path):
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        path = (self.root / check_key(key)).resolve()
        # Belt and braces: the pattern already forbids traversal, but the
        # resolved path is what the OS will open, so that is what is checked.
        if self.root != path and self.root not in path.parents:
            raise ArtifactError("storage key escapes the artifact directory")
        return path

    def put(self, key: str, data: bytes, content_type: str) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(path.name + f".{uuid.uuid4().hex}.part")
        try:
            temporary.write_bytes(data)
            temporary.replace(path)   # atomic: a reader never sees half a file
        finally:
            if temporary.exists():
                temporary.unlink()

    def get(self, key: str) -> bytes:
        path = self._path(key)
        if not path.is_file():
            raise ArtifactNotFound(key)
        return path.read_bytes()

    def delete(self, key: str) -> None:
        path = self._path(key)
        if path.is_file():
            path.unlink()

    def exists(self, key: str) -> bool:
        return self._path(key).is_file()

    def healthy(self) -> bool:
        probe = self.root / f".probe-{uuid.uuid4().hex}"
        try:
            probe.write_bytes(b"ok")
            probe.unlink()
            return True
        except OSError:
            return False


class DatabaseArtifactStore:
    """Bytes in the `artifact_blobs` table.

    For deployments with a managed Postgres and no object storage. Files here
    are small (a PDF is tens of kilobytes); audio uploads are the exception and
    are the reason to move to object storage as usage grows.
    """

    name = "database"

    def __init__(self, database: Any):
        self.database = database

    def put(self, key: str, data: bytes, content_type: str) -> None:
        check_key(key)
        with self.database.connection() as conn:
            conn.execute("DELETE FROM artifact_blobs WHERE storage_key = ?", (key,))
            conn.execute("INSERT INTO artifact_blobs (storage_key, data) VALUES (?, ?)", (key, data))
            conn.commit()

    def get(self, key: str) -> bytes:
        check_key(key)
        with self.database.connection() as conn:
            row = conn.execute("SELECT data FROM artifact_blobs WHERE storage_key = ?", (key,)).fetchone()
            conn.rollback()
        if row is None:
            raise ArtifactNotFound(key)
        return bytes(row["data"])

    def delete(self, key: str) -> None:
        check_key(key)
        with self.database.connection() as conn:
            conn.execute("DELETE FROM artifact_blobs WHERE storage_key = ?", (key,))
            conn.commit()

    def exists(self, key: str) -> bool:
        check_key(key)
        with self.database.connection() as conn:
            row = conn.execute("SELECT 1 AS present FROM artifact_blobs WHERE storage_key = ?", (key,)).fetchone()
            conn.rollback()
        return row is not None

    def healthy(self) -> bool:
        try:
            with self.database.connection() as conn:
                conn.execute("SELECT 1 FROM artifact_blobs LIMIT 0")
                conn.rollback()
            return True
        except Exception:
            return False


def sigv4_headers(
    *, method: str, host: str, path: str, region: str, access_key: str, secret_key: str,
    payload_sha256: str, now: dt.datetime, extra_headers: dict[str, str] | None = None,
    service: str = "s3",
) -> dict[str, str]:
    """AWS Signature Version 4 headers for one request. Pure, so it can be tested offline."""
    amz_date = now.strftime("%Y%m%dT%H%M%SZ")
    date = now.strftime("%Y%m%d")
    headers = {"host": host, "x-amz-content-sha256": payload_sha256, "x-amz-date": amz_date}
    for name, value in (extra_headers or {}).items():
        headers[name.lower()] = " ".join(value.split())
    signed = ";".join(sorted(headers))
    canonical = "\n".join([
        method, quote(path, safe="/-_.~"), "",
        "".join(f"{k}:{headers[k]}\n" for k in sorted(headers)), signed, payload_sha256,
    ])
    scope = f"{date}/{region}/{service}/aws4_request"
    to_sign = "\n".join(["AWS4-HMAC-SHA256", amz_date, scope, hashlib.sha256(canonical.encode()).hexdigest()])

    def sign(key: bytes, message: str) -> bytes:
        return hmac.new(key, message.encode(), hashlib.sha256).digest()

    key = sign(sign(sign(sign(f"AWS4{secret_key}".encode(), date), region), service), "aws4_request")
    signature = hmac.new(key, to_sign.encode(), hashlib.sha256).hexdigest()
    out = {k: v for k, v in headers.items() if k != "host"}
    out["authorization"] = (
        f"AWS4-HMAC-SHA256 Credential={access_key}/{scope}, SignedHeaders={signed}, Signature={signature}"
    )
    return out


class S3ArtifactStore:
    """S3-compatible object storage (AWS S3, Cloudflare R2, MinIO), path-style.

    UNVERIFIED AGAINST A LIVE BUCKET. The request signing is tested against
    AWS's published example; the HTTP calls have only been exercised with a
    fake transport. Run `python -m arranger_api.artifacts --check` against the
    real bucket before relying on it.
    """

    name = "s3"

    def __init__(self, *, endpoint: str, bucket: str, region: str, access_key: str, secret_key: str,
                 client: Any = None, timeout: float = 30.0):
        if not (endpoint.startswith("https://") or endpoint.startswith("http://")):
            raise ArtifactError("S3 endpoint must be a URL")
        if not re.fullmatch(r"[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]", bucket):
            raise ArtifactError("invalid S3 bucket name")
        self.endpoint = endpoint.rstrip("/")
        self.host = self.endpoint.split("://", 1)[1]
        self.bucket, self.region = bucket, region
        self._access_key, self._secret_key = access_key, secret_key
        self._client = client
        self.timeout = timeout

    def _http(self):
        if self._client is None:
            import httpx

            self._client = httpx.Client(timeout=self.timeout)
        return self._client

    def _request(self, method: str, key: str, data: bytes = b"", content_type: str | None = None):
        path = f"/{self.bucket}/{check_key(key)}"
        extra = {"content-type": content_type} if content_type else {}
        headers = sigv4_headers(
            method=method, host=self.host, path=path, region=self.region, access_key=self._access_key,
            secret_key=self._secret_key, payload_sha256=sha256_hex(data),
            now=dt.datetime.now(dt.timezone.utc), extra_headers=extra,
        )
        try:
            return self._http().request(method, self.endpoint + path, content=data or None, headers=headers)
        except Exception as exc:   # transport errors, whatever the client library calls them
            raise ArtifactError(f"object storage request failed: {type(exc).__name__}") from exc

    def put(self, key: str, data: bytes, content_type: str) -> None:
        response = self._request("PUT", key, data, content_type)
        if response.status_code not in (200, 201, 204):
            raise ArtifactError(f"object storage PUT returned {response.status_code}")

    def get(self, key: str) -> bytes:
        response = self._request("GET", key)
        if response.status_code == 404:
            raise ArtifactNotFound(key)
        if response.status_code != 200:
            raise ArtifactError(f"object storage GET returned {response.status_code}")
        return response.content

    def delete(self, key: str) -> None:
        response = self._request("DELETE", key)
        if response.status_code not in (200, 204, 404):
            raise ArtifactError(f"object storage DELETE returned {response.status_code}")

    def exists(self, key: str) -> bool:
        return self._request("HEAD", key).status_code == 200

    def healthy(self) -> bool:
        try:
            return self._request("HEAD", "healthcheck/probe.bin").status_code in (200, 404)
        except ArtifactError:
            return False


def build_artifact_store(settings: Any, database: Any) -> ArtifactStore:
    backend = settings.artifact_backend
    if backend == "local":
        return LocalArtifactStore(settings.artifact_dir)
    if backend == "database":
        return DatabaseArtifactStore(database)
    if backend == "s3":
        return S3ArtifactStore(
            endpoint=settings.s3_endpoint, bucket=settings.s3_bucket, region=settings.s3_region,
            access_key=settings.s3_access_key, secret_key=settings.s3_secret_key,
        )
    raise ArtifactError(f"unknown ARTIFACT_BACKEND '{backend}'")


if __name__ == "__main__":   # pragma: no cover - operator tool
    import sys

    from .settings import load_settings
    from .storage import Database

    _settings = load_settings()
    _store = build_artifact_store(_settings, Database.from_settings(_settings))
    if "--check" in sys.argv:
        _key = f"healthcheck/{uuid.uuid4().hex}.bin"
        _store.put(_key, b"arranger", "application/octet-stream")
        assert _store.get(_key) == b"arranger", "read back different bytes"
        _store.delete(_key)
        assert not _store.exists(_key), "delete did not take effect"
        print(f"{_store.name}: put, get, delete and exists all work")
